In [11]:
import numpy as np
import pandas as pd
from sklearn import svm
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from sklearn import datasets 

In [8]:
x=[[1,2,3],[11,18,16],[22,27,26],[33,34,39]]
y=[1,1,2,2]
clf=svm.SVC(probability=True,kernel='poly', degree=2,gamma=0.1,coef0=1)
clf.fit(x,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=1,
  decision_function_shape='ovr', degree=2, gamma=0.1, kernel='poly',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
print(clf.predict_proba([[10,15,13]]))

[[0.62913274 0.37086726]]


In [11]:
x=[[1,2,3],[11,18,16],[22,27,26],[33,34,39]]
y=[2,1,2,3]
clf=svm.SVC(probability=True,kernel='rbf', degree=2,gamma=0.1,decision_function_shape="ovr",class_weight={1:10})
clf.fit(x,y)
print(clf.predict([[10,15,13]]))
print(clf.predict_proba([[10,15,13]]))
print(clf.decision_function([[10,15,13]]))

[2]
[[0.23039413 0.44680601 0.32279986]]
[[ 1.01201676  2.48798324 -0.5       ]]


In [12]:
x=[[1,2,3],[11,18,16],[22,27,26],[33,34,39]]
y=[1,1,2,3]
clf=svm.SVC(probability=True,kernel='rbf', degree=2,gamma=0.1,random_state=2,decision_function_shape="ovr")
clf.fit(x,y)
print(clf.predict([[10,15,13]]))
print(clf.predict_proba([[10,15,13]]))
print(clf.decision_function([[10,15,13]]))

[1]
[[0.34890691 0.32548254 0.32561055]]
[[ 2.5   0.75 -0.25]]


In [13]:
x=[[1,2,3],[11,18,16],[22,27,26],[33,34,39]]
y=[1,1,2,3]
clf=svm.SVC(probability=True,kernel='rbf', degree=2,gamma=0.1,random_state=2,decision_function_shape="ovo")
clf.fit(x,y)
print(clf.predict([[10,15,13]]))
print(clf.predict_proba([[10,15,13]]))
print(clf.decision_function([[10,15,13]]))

[1]
[[0.34890691 0.32548254 0.32561055]]
[[5.74784310e-01 5.74784310e-01 1.42148466e-20]]


In [16]:
iris = datasets.load_iris() 

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=0)

clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

clf.score(X_test, y_test)  

0.9666666666666667